schemaVersion: '2.0.0'
commandTests:
  - name: "Check Alpine version"
    command: "cat"
    args: ["/etc/os-release"]
    expectedOutput: ["Alpine Linux"]
fileExistenceTests:
  - name: "Check if /etc/passwd exists"
    path: "/etc/passwd"
    shouldExist: true
fileContentTests:
  - name: "Check /etc/os-release content"
    path: "/etc/os-release"
    expectedContents: ["Alpine Linux"]