# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

#       - name: Install snap & aws
#         run: |
#           sudo apt install snapd
#           snap version
#           sudo snap install aws-cli --classic
# 
#           echo "==============================="
#           echo "SNAP & AWS CLI INSTALLED"
#           echo "==============================="
# 
      - name: Clean local repo
        run: |
          rm -rf generated/
          mkdir generated
          rm -rf deployed/
          mkdir deployed

      - name: Install and run kustomize
        uses: syntaqx/setup-kustomize@v1
        with:
          kustomize-version: 5.0.1
      - run: |
          kustomize version

          echo $(kustomize build .)

          kustomize build . > generated/manifests.yaml

#       - name: Validate yaml
#         run: kubeconform -summary -skip CustomResourceDefinition generated/
#   
#       - name: Get Diff
#         run: |
#           flux pull artifact oci://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_ECR_REPOSITORY:latest \
#             --output deployed \
#             --provider aws
#           colordiff -u deployed/manifests.yaml generated/manifests.yaml
#   
#       - name: Push Artifact
#         run: |
#           flux push artifact oci://$AWS_ACCOUNT_ID.dkr.ecr.$env.AWS_REGION.amazonaws.com/$env.AWS_ECR_REPOSITORY:latest \
#            --path="./generated/" \
#             --source="$(git config --get remote.origin.url)" \
#             --revision="$(git tag --points-at HEAD)@sha1:$(git rev-parse HEAD)" \
#             --provider aws
  