name: CI

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  Checkout_and_AWS_Credentials:
    runs-on: ubuntu-latest
    environment: DEV
    permissions:
      id-token: write
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Export environment variables
        run: |
          export AWS_ARN_ROLE=${{ secrets.AWS_ARN_ROLE }}
          export AWS_REGION=${{ secrets.AWS_REGION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: $AWS_ARN_ROLE
          aws-region: eu-west-1

  Pipeline_CI_CD:
    runs-on: ubuntu-latest
    environment: DEV
    needs: Checkout_and_AWS_Credentials

    steps:
      - uses: actions/checkout@v4

      - name: Clean local repo
        run: |
          rm -rf generated/
          mkdir generated
          rm -rf deployed/
          mkdir deployed

  #     - name: Validation with kustomize and kubeconform 
  #       run: |
  #         kustomize build . > generated/manifests.yaml
  #         kubeconform -summary -skip CustomResourceDefinition generated/
      
  #     - name: Get Diff
  #       run: |
  #         flux pull artifact oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest \
  #         --output deployed \
  #         --provider aws
  #         colordiff -u deployed/manifest.yaml generated/manifests.yaml || true
      
  #     - name: Push Artifact
  #       run: |
  #         flux push artifact oci://$AWS_ACCOUNT_ID.dkr.ecr.$env.AWS_REGION.amazonaws.com/$env.AWS_ECR_REPOSITORY:latest \
  #         --path="./generated/" \
  #         --source="$(git config --get remote.origin.url)" \
  #         --revision="$(git tag --points-at HEAD)@sha1:$(git rev-parse HEAD)" \
  #         --provider aws
